### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by magnus-ra** [veraPDF/veraPDF-apps#111]
GIU Version 027.28
When validating some PDF files I have got the error messages as:
“Some error in saving the HTML report: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Ogiltig<invalid> byte 1 i UTF-8-sekvensen för 1-byte”. 
The last figure have been from 1 to 4-byte. The first figure is mostly byte 2. 
In the cases I experienced the files then was “compliant” when it was “4-bytes” but “not compliant” in the other cases.

![error_1](https://cloud.githubusercontent.com/assets/14328270/20867391/44acf9de-ba43-11e6-9a5a-69e651c3e2ef.JPG)
[FiF SG Protokoll 2015-09-23.pdf](https://github.com/veraPDF/veraPDF-apps/files/629635/FiF.SG.Protokoll.2015-09-23.pdf)
![error_2](https://cloud.githubusercontent.com/assets/14328270/20867402/6a4898b0-ba43-11e6-9f70-ea71e125f974.JPG)
[GRÖNBOK 2016 tryckt pdf.pdf](https://github.com/veraPDF/veraPDF-apps/files/629639/GRONBOK.2016.tryckt.pdf.pdf)
![error_3](https://cloud.githubusercontent.com/assets/14328270/20867409/9795ff92-ba43-11e6-86e8-bee3c2b57822.JPG)
[Grundkarta m arbetsområde Model (1).pdf](https://github.com/veraPDF/veraPDF-apps/files/629641/Grundkarta.m.arbetsomrade.Model.1.pdf)
![error_4](https://cloud.githubusercontent.com/assets/14328270/20867414/a423fa7a-ba43-11e6-8dd0-82d589b12788.JPG)
[161011_Agenda_storgruppsmöte_1.pdf](https://github.com/veraPDF/veraPDF-apps/files/629642/161011_Agenda_storgruppsmote_1.pdf)

**Comment by carlwilson** [comment]
This looks like a character set issue, possibly with the output XML stream. @BezrukovM could you investigate please.

**Comment by bdoubrov** [comment]
Duplicates veraPDF/veraPDF-library#644

**Comment by BezrukovM** [comment]
fixed
