### ISSUE TITLE
All "Succeed"

### ISSUE THREAD

**Issue by magnus-ra** [veraPDF/veraPDF-apps#112]
GIU Version 027.28
Testing many files gives me the result message “Succeed” concerning all files, although some files were “not compliant” and although error messages occurred on some of the files, if validating them individually.

**Comment by carlwilson** [comment]
I think that this is just confusing "mixed messages", the succeeded means that the jobs themselves completed normally, with no exceptions. This doesn't mean that the files were all valid, just that the process completed normally.
