### ISSUE TITLE
Feature output missing in HTML reports

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-apps#116]
Applies to veraPDF 0.26.16.

In the VeraPDF GUI, 'feature' output is missing in the HTML reports if 'Report type' is set to 'Features' or 'Validation and Features'. (XML reports work as expected.)

**Comment by carlwilson** [comment]
I'm sure that currently, we don't convert the Features Report to HTML as it's a little wild. We are looking at better ways to configure and invoke the feature extractor, it's not impossible that we'll add HTML support for some commonly used fields but possibly not for the final release. I've assigned this to @BezrukovM as the person most likely to do the work when it comes along.

**Comment by carlwilson** [comment]
We've implemented a minimalist start to solving this issue. if there's anything specific you'd like to see please submit another issue thanks.
