### ISSUE TITLE
Unclear scope of 'feature' output

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-apps#117]
Applies to veraPDF 0.26.16.

The CLI has an `-x` option that 'extracts and reports PDF features'.  I tested the option on a number of PDFs, but from what I can gather it only extracts metadata that are either part of a Document Information Dictionary or as embedded as XMP in a metadata stream (not completely sure about the latter).

E.g. here's the feature output for a simple PDF ([link](https://github.com/openpreserve/format-corpus/raw/master/office-examples/OpenOffice.org%203.2.0%20OSX/pdf-features/simple-PDFA-1a.pdf)):

      <featuresReport xmlns="http://www.verapdf.org/MachineReadableReport">
        <informationDict>
          <entry xmlns:ns2="http://www.verapdf.org/MachineReadableReport" ns2:key="Author">Andrew Jackson</entry>
          <entry xmlns:ns2="http://www.verapdf.org/MachineReadableReport" ns2:key="Creator">Writer</entry>
          <entry xmlns:ns2="http://www.verapdf.org/MachineReadableReport" ns2:key="Producer">OpenOffice.org 3.2</entry>
          <entry xmlns:ns2="http://www.verapdf.org/MachineReadableReport" ns2:key="CreationDate">2010-03-10T15:09:14.000Z</entry>
        </informationDict>
      </featuresReport>

Now compare this against the ExifTool output for the same file: 

    ExifTool Version Number         : 9.46
    File Name                       : simple-PDFA-1a.pdf
    Directory                       : .
    File Size                       : 25 kB
    File Modification Date/Time     : 2012:11:23 13:16:27+01:00
    File Access Date/Time           : 2016:12:07 13:49:54+01:00
    File Inode Change Date/Time     : 2016:08:15 14:42:11+02:00
    File Permissions                : rw-------
    File Type                       : PDF
    MIME Type                       : application/pdf
    PDF Version                     : 1.4
    Linearized                      : No
    Page Count                      : 1
    Language                        : en-US
    Tagged PDF                      : Yes
    Part                            : 1
    Conformance                     : A
    Creator                         : Andrew Jackson
    Producer                        : OpenOffice.org 3.2
    Creator Tool                    : Writer
    Create Date                     : 2010:03:10 15:09:14Z
    Author                          : Andrew Jackson

The VeraPDF feature report misses basic characteristics such as the PDF version number (1.4), file modification / access dates, page count, linearization and language, which are all defined outside the DID. Don't know if this is meant to be added to VeraPDF at some later stage (hope so!). If not, I'd  suggest to change the description of the `x` switch to 'extract metadata' or something along those lines (and explain in the docs the scope of the feature output).

**Comment by carlwilson** [comment]
Hi @bitsgalore the software does support further options for features, they're controlled by a config file `<install dir>/config/features.xml` OR via the GUI File/Features Config setting (which updates the config file). Initially the file reads:

    <featuresConfig>
        <enabledFeatures>
            <feature>INFORMATION_DICTIONARY</feature>
        </enabledFeatures>
    </featuresConfig>
but heres an "all features on" goodness config that you can try:

    <featuresConfig>
        <enabledFeatures>
            <feature>ANNOTATION</feature>
            <feature>COLORSPACE</feature>
            <feature>DOCUMENT_SECURITY</feature>
            <feature>EMBEDDED_FILE</feature>
            <feature>EXT_G_STATE</feature>
            <feature>FONT</feature>
            <feature>FORM_XOBJECT</feature>
            <feature>ICCPROFILE</feature>
            <feature>IMAGE_XOBJECT</feature>
            <feature>INFORMATION_DICTIONARY</feature>
            <feature>LOW_LEVEL_INFO</feature>
            <feature>METADATA</feature>
            <feature>OUTLINES</feature>
            <feature>OUTPUTINTENT</feature>
            <feature>PAGE</feature>
            <feature>PATTERN</feature>
            <feature>POSTSCRIPT_XOBJECT</feature>
            <feature>PROPERTIES</feature>
            <feature>SHADING</feature>
            <feature>SIGNATURE</feature>
            <feature>FAILED_XOBJECT</feature>
            <feature>ERROR</feature>
        </enabledFeatures>
    </featuresConfig>
Documentation is weak again and will be improved for the end of the year.
