### ISSUE TITLE
Message only ;)

### ISSUE THREAD

**Issue by JurajStrnisko** [veraPDF/veraPDF-apps#155]
Dear Boris,
we spoke together at Preforma INNOVATION workshop last week. At that time I've told you, that I wasn't able to run verapdf-1.0.6-PDFBOX on my debian 8.7 (jessie) machine.
However I've found out, that the issue was java - after I re-installed openjdk-7-jre and install the latest verapdf version - verapdf-1.2.1-PDFBOX it works OK.

Regards,
Juraj Strnisko

**Comment by bdoubrov** [comment]
Very good! Thanks for letting us know.
