### ISSUE TITLE
False negative if Standard 14 named font is embedded

### ISSUE THREAD

**Issue by THausherr** [veraPDF/veraPDF-apps#156]
see https://issues.apache.org/jira/secure/attachment/12861628/test42-Roman.pdf
from https://issues.apache.org/jira/browse/PDFBOX-3740 . This file validates with https://www.pdf-online.com/osa/validate.aspx . The cause is a bug in PDFBox.

I'm using the VeraPDF GUI 1.2.1.

**Comment by bdoubrov** [comment]
Issue confirmed. Will fix it in the coming release

**Comment by bdoubrov** [comment]
Fixed in veraPDF 1.4 (version 1.4.1)
