### ISSUE TITLE
Running CLI app for multiple PDFs only gives output for 1 PDF

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-apps#171]
I'm trying to run veraPDF (1.4.6) on multiple PDFs at a time like this: 

     verapdf /home/johan/format-corpus/pdfCabinetOfHorrors/text*.pdf > textall.xml

However in each case the output report only contains one *job* element (which corresponds to one single PDF), whereas I would expect mutiple (for each PDF that matches the glob pattern).

**Comment by BezrukovM** [comment]
Fixed in versions 1.4.7 and 1.5.22
