### ISSUE TITLE
Policy check fails with  external Schematron validator, but unexpectedly passes with VeraPDF

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-apps#173]
I created a the following Schematron policy file that will flag PDFs with any kind of encryption:

    <sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt">
        <sch:pattern name="Disallow encryption.">
            <sch:rule context="/report/jobs/job/validationReport/details/rule">
                <sch:assert test="not(@specification='ISO 19005-1:2005' and @clause='6.1.3' and @status='failed')">Encrypt in trailer dictionary is not allowed.</sch:assert>
            </sch:rule>
            <sch:rule context="/report/batchSummary">
                <sch:assert test="not(@encrypted='1')">Encryption with open password is not allowed.</sch:assert>
            </sch:rule>
        </sch:pattern>
    </sch:schema>

Link to PDF with 'open password':

<https://github.com/openpreserve/format-corpus/raw/master/pdfCabinetOfHorrors/encryption_openpassword.pdf>

This file should trigger a violation of the second rule in the above policy file. Here's my veraPDF invocation:

    verapdf --policyfile no-encryption.sch encryption_openpassword.pdf > encryption_openpassword.xml

Resulting output file:

   <?xml version="1.0" encoding="UTF-8"?><report>
    <buildInformation>
    <releaseDetails id="gui" version="1.4.6" buildDate="2017-05-15T11:05:00+02:00"/>
    <releaseDetails id="core" version="1.4.1" buildDate="2017-04-20T02:02:00+02:00"/>
    <releaseDetails id="validation-model" version="1.4.7" buildDate="2017-05-15T10:58:00+02:00"/>
    </buildInformation>
    <jobs>
    <job>
    <item size="70599">
    <name>/home/johan/veraPDFPolicies/./test/encryption_openpassword.pdf</name>
    </item>
    <taskResult type="PARSE" isExecuted="true" isSuccess="false">
    <duration start="1495465682326" finish="1495465682374">00:00:00:048</duration>
    <exceptionMessage>Exception: The PDF stream appears to be encrypted. caused by exception: Reader::init(...)encrypted pdf is not supported</exceptionMessage>
    </taskResult>
    <duration start="1495465682326" finish="1495465682374">00:00:00:048</duration>
    <policyReport passedChecks="0" failedChecks="0" xmlns:vera="http://www.verapdf.org/MachineReadableReport">
    <passedChecks/>
    <failedChecks/>
    </policyReport>
    </job>
    </jobs>
    <batchSummary totalJobs="1" failedToParse="0" encrypted="1">
    <validationReports compliant="0" nonCompliant="0" failedJobs="1">1</validationReports>
    <featureReports failedJobs="1">1</featureReports>
    <repairReports failedJobs="0">0</repairReports>
    <duration start="1495465682316" finish="1495465682388">00:00:00:072</duration>
    </batchSummary>
    </report>
    
Note that value of *failedChecks* in *policyReport* element equals 0 (expected 1), and *failedChecks* element is empty (policy check passes, which is unexpected). However, when I do a schematron validation on the Verapdf output for this file with an external Schematron validator (here I used [this Shell script that is based on the schematron reference implementation](https://github.com/bitsgalore/schematronValidate.bat)) I end up with this (which is what I would expect):
 
    <?xml version="1.0" standalone="yes"?>
    <svrl:schematron-output xmlns:svrl="http://purl.oclc.org/dsdl/svrl" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:schold="http://www.ascc.net/xml/schematron" xmlns:sch="http://www.ascc.net/xml/schematron" xmlns:iso="http://purl.oclc.org/dsdl/schematron" title="" schemaVersion="">
      
      <svrl:active-pattern/>
      <svrl:fired-rule context="/report/batchSummary"/>
      <svrl:failed-assert test="not(@encrypted='1')" location="/report/batchSummary">
        <svrl:text>Encryption with open password is not allowed.</svrl:text>
      </svrl:failed-assert>
    </svrl:schematron-output>
 
So in this case the policy check fails (which is expected), using the very same Schematron file!

**Comment by BezrukovM** [comment]
Our policy checks logic bounds to job elements. So If there will be any policy rules/assertions which are applied to any nested nodes of jobs element, then you will see their results inside job element.. All results which are not applied to nested nodes of job element will not be merged into complete report.

So one of the ways to make such policy check is to test context="/report/jobs/job/taskResult/exceptionMessage" on existing and containing "The PDF stream appears to be encrypted", "encrypted pdf is not supported" or just "encrypted" substring inside its value.

**Comment by bitsgalore** [comment]
Thanks, that makes sense. I just tried your suggestion and I can confirm it works, so I'll close this issue now.
