### ISSUE TITLE
Profiling for JavaScript not possible because Action types not reported in feature output

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-apps#174]
I just tried to set up a Schematron profile for checking on the presence of JavaScript. However, as far as I can tell there's no way to report JavaScript in the *feature* output. The only indication that a PDF might contain JavaScript is now rule ISO 19005-1:2005, clause 6.6.1 in the validation output, which checks for a number of *Actions* that are not allowed in PDF/A-1. But even this is not very specific, as it includes several other *Action* types.

My suggestion would be to add a new *enabledFeatures* group called *ACTION*, which reports all *Action* types in a PDF. See also section 12.6.4 (Action Types) in ISO 320000. This would also allow more fine-grained profiling for specific interactive and multimedia features.

**Comment by BezrukovM** [comment]
Added in PRs:
https://github.com/veraPDF/veraPDF-library/pull/776
https://github.com/veraPDF/veraPDF-validation/pull/185
https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/159
