### ISSUE TITLE
1.4.6 # PDFBox or GF?

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-apps#189]
Save for using, and remembering, a download link such as
-- http://downloads.verapdf.org/dev/verapdf-gf-installer.zip
-- http://downloads.verapdf.org/dev/1.5/verapdf-1.5.9-PDFBOX-installer.zip
-- http://downloads.verapdf.org/rel/1.4/verapdf-1.4.7-PDFBOX-installer.zip

**how to determine whether the version that is running/installed is using PB or GF?**
No indication from
-- 1.4.6. GUI "help: about" nor GUI --version.

Cf http://downloads.verapdf.org/rel/verapdf-installer.zip

**Comment by carlwilson** [comment]
Hi @beyo-ra from the CLI type `verapdf --version`:

PDFBox 1.4.7:
```
$ ~/verapdf/1.4/verapdf --version
veraPDF 1.4.7-PDFBOX
Built: Wed May 24......
```
Note the `-PDFBOX` release qualifier. If this is absent then it's the Greenfield version:
```
$ ~/verapdf/1.4/verapdf --version
veraPDF 1.4.7
Built: Wed May 24...
```
The screenshots below are of the About panel of the PDFBox GUI:
![image](https://cloud.githubusercontent.com/assets/440634/26522888/65a318ce-4302-11e7-8271-be3826fb11b3.png)
again the `-PDFBOX` qualifer which is absent for the Greenfield version:
![image](https://cloud.githubusercontent.com/assets/440634/26522910/dfc0faea-4302-11e7-8c94-1efa38c87afe.png)
