### ISSUE TITLE
Unclear what condition(s) trigger(s) 'PDF stream appears to be encrypted' exception 

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-apps#202]
All 'encryption' examples in the OPF ['PDF Cabinet of Horrors' corpus](https://github.com/openpreserve/format-corpus/tree/master/pdfCabinetOfHorrors) can be parsed without problems (this includes disabled printing, copying and text extraction), except the 'open password' file. This is also what I expected.

However, [attached file *MultiMedia_Acro6.pdf*](https://github.com/veraPDF/veraPDF-apps/files/1041984/MultiMedia_Acro6.pdf) (which originates from the old Acrobat Engineering website) results in an exception:

    <exceptionMessage>Exception: The PDF stream appears to be encrypted. caused by exception: Reader::init(...)encrypted pdf is not supported</exceptionMessage>

It's not enirely clear to me *why* this exception occurs, as the file has no 'open password' (it can be opened normally in a reader). I opened the file in Acrobat and checked the 'Security' tab under 'Document Properties'. This shows that apart from 'Content Copying for Accessibility' all possible restrictions are set to 'Not Allowed'.

This makes me wonder if the behaviour I'm getting is as intended, and if yes *which* specific restriction(s) trigger(s) the 'encrypted PDF' error. (I was previously able to parse this file with Apache Preflight; also I have a couple of other PDFs that result in the same behaviour).

Using version 1.4.7.

**Comment by shem-sergey** [comment]
Here there is just a bug.
Generally speaking, verapdf processes all the encrypted files that can be decrypted with empty password string (these files can be opened in pdf viewers without asking for password).

**Comment by bitsgalore** [comment]
Already suspected this, good to see this fixed!
