### ISSUE TITLE
VeraPDF not handling large (10 GB, 750pp) PDFs?

### ISSUE THREAD

**Issue by kai-h** [veraPDF/veraPDF-apps#212]
I have set up a workflow where I am taking a number of scanned images in TIFF format, converting the TIFF to individual PostScript files and then distilling them to PDF using GhostScript. I have set up custom .joboptions and PDFA_def.ps files for GhostScript and creating valid PDF/A-2B files.
I'm merging these files into multi-page PDFs and these are valid PDF/A-2B files. I have verified them with VeraPDF and Acrobat Pro and they check out OK.
When I'm creating large PDFs - an example I have is 750 pages and 10 GB in size, VeraPDF is reporting that the file doesn't appear to be a valid PDF.

[kai@hobbes ~]$ /Applications/verapdf/verapdf --format text /Volumes/Data/Failed\ PDF\ files/Sample\ failed.pdf 
Jun 09, 2017 10:38:22 PM org.verapdf.processor.ProcessorImpl process
WARNING: /Volumes/Data 1/Failed PDF files/Sample failed.pdf doesn't appear to be a valid PDF.
/Volumes/Data 1/Failed PDF files/Sample failed.pdf does not appear to be a valid PDF file and could not be parsed.

Does VeraPDF have any known issues with large files?

**Comment by BezrukovM** [comment]
The problem has been in offsets more than int value (>2gb files). Has been fixed now (veraPDF 1.10.5)
