### ISSUE TITLE
[ERR 0510]/[ERR XTSE0090]  when using --policyfile

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-apps#232]
I'm using veraPDF 1.8.4 on Linux Mint. The following command used to work with earlier versions of PDF:

    verapdf -x --maxfailuresdisplayed 1 --policyfile demo-policy.sch text_only_fontsNotEmbedded.pdf  > out.xml 2> stderr.txt

I'm using this policy file: <https://github.com/KBNLresearch/pdfPolicyVeraPDF/blob/master/schemas/demo-policy.sch>

This results in the following error and warning messages:

    ERROR:  '[ERR 0510][ERR XTSE0090] The illegal attribute 'select' is specified.; Line#: 16; Column#: 26'
    WARNING:  '[WARNING 0015] The document() function was not able to load the requested document 'file:/tmp/policyResult7108668580322642021veraPDF'.  An empty node-set was returned.; Line#: 30; Column#: 142'
           :Content is not allowed in prolog.
    WARNING:  '[WARNING 0015] The document() function was not able to load the requested document 'file:/tmp/policyResult7108668580322642021veraPDF'.  An empty node-set was returned.; Line#: 29; Column#: 138'
           :Content is not allowed in prolog.
    WARNING:  '[WARNING 0015] The document() function was not able to load the requested document 'file:/tmp/policyResult7108668580322642021veraPDF'.  An empty node-set was returned.; Line#: 41; Column#: 120'
           :Content is not allowed in prolog.
    WARNING:  '[WARNING 0015] The document() function was not able to load the requested document 'file:/tmp/policyResult7108668580322642021veraPDF'.  An empty node-set was returned.; Line#: 57; Column#: 116'
           :Content is not allowed in prolog.

I'm getting these messages for every PDF I throw at VeraPDF.

**Comment by bdoubrov** [comment]
Thanks for reporting this issues. I think we reproduced it on our local system as well. 

It looks like these messages come from Schematron compiler scripts. Do they affect the resulting veraPDF report?

**Comment by carlwilson** [comment]
Hi @bitsgalore could you please let us know the Java JVM (openjdk ?) and version you're running also please? Thanks.

**Comment by bitsgalore** [comment]
@carlwilson 

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 8.0.5.0 - pxa6480sr5-20170905_01(SR5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20170901_363591 (JIT enabled, AOT enabled)
J9VM - d56eb84
JIT  - tr.open_20170901_140853_d56eb84
OMR  - b033a01)
JCL - 20170823_01 based on Oracle jdk8u144-b01

**Comment by carlwilson** [comment]
Thanks :)

**Comment by bitsgalore** [comment]
@bdoubrov 

Yes, the resulting report does contain a policyReport element but it doesn't contain any meaningful info. Here's an example:
```
<policyReport xmlns:vera="http://www.verapdf.org/MachineReadableReport" passedChecks="0" failedChecks="0">
<passedChecks/>
<failedChecks/>
</policyReport>
```

**Comment by BezrukovM** [comment]
@bitsgalore the 1st warning has been fixed.
About other warnings: I could not reproduce them on my machine (Linux Ubuntu), but we have made an improvement on loading documents in policy logic. As all of your warnings are belongs to document loading, can you double check that issue on last dev version (1.9.80), please?

**Comment by bitsgalore** [comment]
@BezrukovM After some tests I can confirm that the error and the warnings are gone in 1.9.84; also the policy output is now as expected. Thanks for fixing this!
