### ISSUE TITLE
v0.20.3 CLI :~$ ./verapdf # blocking if no input given: should provide help.

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-apps#52]
Concerning v. 0.20.3 running on Linux in Konsole.

When accessing the CLI, typing verapdf, if no input given then prompt is blocked/freezes (esc using Ctrl+C).

Expected behavior: if not arguments given: output help, that is, equivalent to, -/verapdf -h.

**Comment by mato7d5** [comment]
if no args are given then verapdf reads input from STDIN. but it seems there is a bug. It won't process input from STDIN (even ctrl+d was pressed).

**Comment by beyo-ra** [comment]
I have not read the code, but as you explain it,
- if no ARGV then read from STDIN
- But if STDIN == NULL then...? Freeze?

Should it not be:
If STDIN == NULL then help
if STDIN not NULL and STDIN contains no ARGV then read from STDIN.

That is, if no argument values given **and** the standard input is not empty then process from standard input.

Cheers!

**Comment by mato7d5** [comment]
There is a bug. VeraPDF won't validate input files from STDIN:
<validationReport>
        <statement>Could not finish validation. Error: STDIN is not a PDF format file.</statement>
    </validationReport>

ModelParser excepts valid file path. 
You're probably right, there should be printed "help" if there is not input as arg.

**Comment by mato7d5** [comment]
https://github.com/veraPDF/veraPDF-apps/pull/54

**Comment by carlwilson** [comment]
Hi all,

I'm not sure that this is a bug as such, if no file arg is given the app will process standard in, allowing piped use. When I test it (Ubuntu 16.04) then Ctrl-D does indeed stop the processing. The following both work as I'd expect:

Just invoke program and kill with CTRL-D:

    cfw@dm-wrkstn:~/verapdf/0.21$ ./verapdf
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <report xmlns="http://www.verapdf.org/MachineReadableReport" creationDate="2016-09-02T10:49:33.880+01:00" processingTime="00:00:01.955" version="0.21.0-SNAPSHOT" buildDate="2016-09-02T09:46:00+01:00">
        <itemDetails size="-1">
            <name>STDIN</name>
        </itemDetails>
        <validationReport>
            <statement>Could not finish validation. Error: STDIN is not a PDF format file.</statement>
        </validationReport>
    </report>

Piping a corpus file from `cat` does validate the file:

    cfw@dm-wrkstn:~/verapdf/0.21$ cat corpus/veraPDF-corpus-staging/PDF_A-1b/6.1\ File\ structure/6.1.10\ Filters/veraPDF\ test\ suite\ 6-1-10-t01-fail-a.pdf | ./verapdf
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <report xmlns="http://www.verapdf.org/MachineReadableReport" creationDate="2016-09-02T10:50:29.487+01:00" processingTime="00:00:00.828" version="0.21.0-SNAPSHOT" buildDate="2016-09-02T09:46:00+01:00">
        <itemDetails size="-1">
            <name>STDIN</name>
        </itemDetails>
        <validationReport profile="PDF/A-1B validation profile" compliant="false">
            <statement>PDF file is not compliant with Validation Profile requirements.</statement>
            <details passedRules="102" failedRules="1" passedChecks="474" failedChecks="1">
                <rule specification="ISO 19005-1:2005" clause="6.1.10" testNumber="1" status="failed" passedChecks="4" failedChecks="1">
                    <description>The LZWDecode filter shall not be permitted</description>
                    <object>CosFilter</object>
                    <test>internalRepresentation != "LZWDecode"</test>
                    <check status="failed">
                        <context>root/indirectObjects[8](9 0)/directObject[0]/filters[0]</context>
                    </check>
                </rule>
            </details>
        </validationReport>
    </report>

as does redirection from a file:

    cfw@dm-wrkstn:~/verapdf/0.21$ ./verapdf < corpus/veraPDF-corpus-staging/PDF_A-1b/6.1\ File\ structure/6.1.10\ Filters/veraPDF\ test\ suite\ 6-1-10-t01-fail-a.pdf
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <report xmlns="http://www.verapdf.org/MachineReadableReport" creationDate="2016-09-02T10:51:08.361+01:00" processingTime="00:00:00.725" version="0.21.0-SNAPSHOT" buildDate="2016-09-02T09:46:00+01:00">
        <itemDetails size="-1">
            <name>STDIN</name>
        </itemDetails>
        <validationReport profile="PDF/A-1B validation profile" compliant="false">
            <statement>PDF file is not compliant with Validation Profile requirements.</statement>
            <details passedRules="102" failedRules="1" passedChecks="474" failedChecks="1">
                <rule specification="ISO 19005-1:2005" clause="6.1.10" testNumber="1" status="failed" passedChecks="4" failedChecks="1">
                    <description>The LZWDecode filter shall not be permitted</description>
                    <object>CosFilter</object>
                    <test>internalRepresentation != "LZWDecode"</test>
                    <check status="failed">
                        <context>root/indirectObjects[8](9 0)/directObject[0]/filters[0]</context>
                    </check>
                </rule>
            </details>
        </validationReport>
    </report>

I do agree that the messaging could be more helpful. I'll look at the PR from @mato7d5 and see what I think. I'll then make a suggestion or two here and we can agree on sensible behaviour. The issue is really around agreeing sensible / graceful behaviour.

Carl

**Comment by carlwilson** [comment]
There's now an alternative behaviour offered by #63, I thought I'd add the example output here so it could be compared with the above:

    cfw@dm-ultra:~/dev/git/veraPDF/apps$ ~/verapdf/0.21/verapdf                                                                                                                                                         
    Usage: veraPDF [options] FILES
      Options:
        -c, --config
           Loads config form default file, all config flags are ignored.
           Default: false
        -x, --extract
           Extract and report PDF features.
           Default: false
        --fixmetadata
           Performs metadata fix.
           Default: false
        -f, --flavour
           Choose built in Validation Profile flavour, e.g. 1b. Alternatively supply
           0 to turn off PDF/A validation or supply auto to automatic flavour
           detection from file's metadata.
           Default: auto
           Possible Values: [0, auto, 1a, 1b, 2a, 2b, 2u, 3a, 3b, 3u]
        --format
           Choose output format:
           Default: mrr
           Possible Values: [xml, mrr, html, text]
        -h, --help
           Shows this message and exits.
           Default: false
        -l, --list
        List built in Validation Profiles.
        Default: false
     --maxfailures
        Sets maximum amount of failed checks.
        Default: -1
     --maxfailuresdisplayed
        Sets maximum amount of failed checks displayed for each rule.
        Default: 100
     --overwriteReportFile
        Overwrite report file.
        Default: false
     --policyProfile
        Uses policy checks output with specified policy profile, output format
        option will be ignored.
        Default: <empty string>
     --prefix
        Prefix for the saved file.
        Default: veraPDF_
     -p, --profile
        Load a Validation Profile from given path and exit if loading fails. This
        overrides any choice or default implied by the -f / --flavour option.
     -pw, --profilesWiki
        The path to the folder containing Validation Profiles wiki.
        Default: https://github.com/veraPDF/veraPDF-validation-profiles/wiki
     -r, --recurse
        Recurse directories, only files with a .pdf extension are processed.
        Default: false
     --reportfile
        Save report to file
        Default: <empty string>
     --reportfolder
        Save reports in folder.
        Default: <empty string>
     --savefolder
        The folder to save the fixed file to.
        Default: <empty string>
     --success, --passed
        Logs successful validation checks.
        Default: false
     -v, --verbose
        Adds failed test information to text output.
        Default: false
     --version
        Version information.
        Default: false

    veraPDF is processing STDIN and is expecting an EOF marker.
    If this isn't your intention you can terminate by typing an EOF equivalent:
    - Linux or Mac users should type CTRL-D
    - Windows users should type CTRL-Z

Issuing an EOF causes the empty stream to be processed thus:

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>                 
    <report xmlns="http://www.verapdf.org/MachineReadableReport" creationDate="2016-09-05T22:51:17.316+01:00" processingTime="00:04:37.199" version="0.21.0-SNAPSHOT" buildDate="2016-09-05T21:33:00+01:00">
        <itemDetails size="-1">
            <name>STDIN</name>
        </itemDetails>
        <validationReport>
            <statement>Could not finish validation. Error: STDIN is not a PDF format file.</statement>
        </validationReport>
    </report>

People may prefer @mato7d5 solution #54, and those people might include me ;) am open to suggestions.
