### ISSUE TITLE
v0.20.3 GUI # Cannot exit GUI using Ctr+Q, Esc, or alternative in menu.

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-apps#53]
Concerning v. 0.20.3 running on Linux using Awesome Windows Manager.

Request/ śuggestion: the GUI should support exit using at least one shortcut command.

**Comment by BezrukovM** [comment]
Added menu item for quit the application and an option to quit by using Ctrl+Q in #57
