### ISSUE TITLE
v0.20.3 CLI # Sometwhat sluggish.

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-apps#61]
Running e.g. veraPDF -h or --version responds in ~0.5-1s.

Cf/See https://github.com/EasyinnovaSL/DPFManager/issues/262.

**Comment by carlwilson** [comment]
I think that the "sluggish" behaviour is actually the overhead of Java Virtual Machine initialisation. This is one of the compromises Java makes for cross-platform goodness, [Wikipedia says a little about it](https://en.wikipedia.org/wiki/Java_performance#Startup_time). Both of the options you mention are parsed out and dealt with quickly in the code, it's simply the time that the JVM takes getting to the code that is the issue. One solution would be to process these options in the startup script BUT that means that the help would need to be written separately (it currently uses a Java lib) and the reported version may not be accurate, or could more easily be changed and mislead.

**Comment by beyo-ra** [comment]
Gee, Java is the culprit behind it all, I would've never... :)

Just to be clear, I am not criticizing the veraPDF or DPFManager code -- as I have not yet reviewed them :)

For the ordinary user, cross-platform and start-up time is however fancy city-folk talk. As I stated in the other post; most users would probably equivalate a slower response time with poor software. 

Mind you, this problem really occurs when requesting --help and --version as a time gap is expected when using the CLI to, e.g., validate it does not feel sluggish in the same sense. 

One solution, that may help, is that you output a text e.g.

    "Please wait, Java Virtual Machine initialization... Loading Java modules... "

Or something like that.

Thus making sure the blame is put in the bucket passed along ;)

**Comment by carlwilson** [comment]
I'm deferring this to the testing phase where we'll look at performance metrics in more detail.

**Comment by carlwilson** [comment]
Closing as we're making good progress on performance and will respond to specific issues raised in future, this is quite general.
