### ISSUE TITLE
v0.20.3 GUI # Choose PDF -> Select multiple files.

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-apps#62]
A request from external PREFORMA <s>partners</s> participants/early users.

Although batch support exists using CLI, and not required for GUI, 
a preference has been expressed for 
- selecting more than 1 file when using "Choose file" in the GUI.

The same functionality has been requested for the WUI.

**Comment by carlwilson** [comment]
I believe that this is just a config flag when creating the SWING Files dialog and should be a quick fix, @BezrukovM could you look at this please.
